# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SMTP-Multipart
version:      1.5.4
version_from: Multipart.pm
installdirs:  site
requires:
    MIME::Base64:                  0
    Net::SMTP:                     0
    Test:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
